import type { Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";
import "@mantine/core/styles.css";
import { MantineProvider, mantineHtmlProps } from "@mantine/core";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ar" {...mantineHtmlProps}>
      <body>
        <ClerkProvider>
          <MantineProvider defaultColorScheme="light">{children}</MantineProvider>
        </ClerkProvider>
      </body>
    </html>
  );
}
